function Ta = ActiveImpedanceControl(l1,l2,th1,th2,thdot1,thdot2,xdott,xt,ydott,yt)
%ActiveImpedanceControl
%    Ta = ActiveImpedanceControl(L1,L2,TH1,TH2,THDOT1,THDOT2,XDOTT,XT,YDOTT,YT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    20-Feb-2025 20:30:01

t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t9 = -yt;
t5 = l1.*t2;
t6 = cos(t4);
t7 = l1.*t3;
t8 = sin(t4);
t10 = l2.*t6;
t11 = l2.*t8;
t12 = t10.*thdot2;
t13 = t11.*thdot2;
t14 = t5+t10;
t15 = t7+t11;
t16 = t15+xt;
t17 = t14.*thdot1;
t18 = t15.*thdot1;
t20 = t9+t14;
t19 = abs(t16);
t22 = abs(t20);
t24 = t12+t17+xdott;
t25 = t13+t18+ydott;
t21 = t19.^2;
t23 = t22.^2;
t26 = abs(t24);
t27 = abs(t25);
t28 = t27.^2;
t29 = t26.^2;
t30 = t21+t23;
t31 = sqrt(t30);
t36 = t28+t29;
t32 = t31.*1.0e+1;
t38 = sqrt(t36);
t33 = -t32;
t39 = t38.*1.0e+1;
t34 = exp(t33);
t40 = -t39;
t35 = t34.*9.9e+1;
t41 = exp(t40);
t37 = t35-1.0e+2;
t43 = t41.*(4.99e+2./1.0e+1);
t42 = t16.*t37;
t44 = t20.*t37;
t46 = t43-5.0e+1;
t47 = t24.*t46;
t48 = t25.*t46;
t49 = t42+t47;
Ta = [t14.*t49-t15.*(t44-t48);t10.*t49-t11.*(t44-t48)];
end
