function Ta = ImpedenceControl(Kd,Kp,g,l1,l2,m1,m2,th1,th2,thdot1,thdot2,xdott,xt,ydott,yt)
%ImpedenceControl
%    Ta = ImpedenceControl(Kd,Kp,G,L1,L2,M1,M2,TH1,TH2,THDOT1,THDOT2,XDOTT,XT,YDOTT,YT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Jul-2025 10:14:47

t2 = cos(th1);
t3 = sin(th1);
t4 = m1+m2;
t5 = th1+th2;
t10 = -yt;
t6 = l1.*t2;
t7 = cos(t5);
t8 = l1.*t3;
t9 = sin(t5);
t11 = g.*t4;
t12 = l2.*t7;
t13 = l2.*t9;
t16 = -t11;
t14 = t12.*thdot2;
t15 = t13.*thdot2;
t17 = t6+t12;
t18 = t8+t13;
t19 = t18+xt;
t20 = t17.*thdot1;
t21 = t18.*thdot1;
t23 = t10+t17;
t22 = Kp.*t19;
t24 = Kp.*t23;
t26 = t14+t20+xdott;
t27 = t15+t21+ydott;
t25 = -t24;
t28 = Kd.*t26;
t29 = Kd.*t27;
t30 = t22+t28;
t31 = t25+t29;
Ta = [-t17.*t30-t18.*max([t31,t16], [], 2, 'omitnan');-t12.*t30-t13.*max([t31,t16], [], 2, 'omitnan')];
end
