function [M,C,G] = MassCoriolisGravity(th1,th2,thdot1,thdot2,m1,m2,l1,l2,d1,d2,I1,I2,g)
%MassCoriolisGravity
%    [M,C,G] = MassCoriolisGravity(TH1,TH2,THDOT1,THDOT2,M1,M2,L1,L2,D1,D2,I1,I2,g)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Jun-2025 11:24:07

t2 = cos(th1);
t3 = sin(th1);
t4 = sin(th2);
t5 = th1+th2;
t6 = d1.^2;
t7 = d2.^2;
t8 = l1.*t2;
t9 = cos(t5);
t10 = l1.*t3;
t11 = sin(t5);
t12 = d2.*t9;
t13 = d2.*t11;
t14 = g.*m2.*t13;
t15 = t8+t12;
t16 = t10+t13;
t17 = t13.*t16.*2.0;
t18 = t12.*t15.*2.0;
t19 = t17+t18;
t20 = (m2.*t19)./2.0;
t21 = I2+t20;
M = reshape([I1+I2+(m1.*(t2.^2.*t6.*2.0+t3.^2.*t6.*2.0))./2.0+(m2.*(t15.^2.*2.0+t16.^2.*2.0))./2.0,t21,t21,I2+(m2.*(t7.*t9.^2.*2.0+t7.*t11.^2.*2.0))./2.0],[2,2]);
if nargout > 1
    C = [thdot2.*(d2.*l1.*m2.*t4.*thdot1.*2.0+d2.*l1.*m2.*t4.*thdot2.*2.0)+d2.*l1.*m2.*t4.*thdot1.*thdot2.*2.0;d2.*l1.*m2.*t4.*thdot1.^2.*-2.0];
end
if nargout > 2
    G = [t14+g.*m2.*t10+d1.*g.*m1.*t3;t14];
end
end
